### ISSUE TITLE
【学习日报】2021-08-23

### ISSUE THREAD

**Issue by qc-z** [cuixiaorui/study-every-day#27]

**Comment by quyapeng** [comment]
![image](https://user-images.githubusercontent.com/8325281/130378411-ebc5779c-26f6-49aa-84c4-c0c88288709e.png)

https://www.wolai.com/aYd4sdV34yysekYkVDK79R?theme=light

**Comment by qc-z** [comment]
![image](https://user-images.githubusercontent.com/22362903/130378785-57e28207-286c-4801-9a31-ea1301e1f4e7.png)

**Comment by kang8** [comment]
![www wolai com_oVQBCm2SBiYTGn6cRNrEFc](https://user-images.githubusercontent.com/36906329/130379301-594fcbe0-53c9-4ccc-90b2-52b2860dd8a6.png)
[传送门](https://www.wolai.com/oVQBCm2SBiYTGn6cRNrEFc?theme=dark)

**Comment by yd160513** [comment]
[今日任务](https://www.wolai.com/wHGwkfsgjNDiTqmjAgVuyR?theme=dark)

![image](https://user-images.githubusercontent.com/34637837/130379403-e82e6d88-bebf-49fb-8068-d2609b93c48b.png)

**Comment by goodboy-qcl** [comment]
![image](https://user-images.githubusercontent.com/73216298/130380664-ae4a2bc3-eb10-40ec-9b63-cea41c063554.png)
传送门[](https://www.wolai.com/bFruyQ31c2gEj8oa5cv72S?theme=light)

**Comment by whylost** [comment]
![image](https://user-images.githubusercontent.com/62528887/130386510-19c972f3-a810-4b29-a368-a0652a1606be.png)

[传送门](https://www.wolai.com/whylost/7fBDMUDQc4NmWk2XpUX419?theme=light)

**Comment by cuixiaorui** [comment]
![image](https://user-images.githubusercontent.com/12064746/130399568-f0d946d7-a674-4040-83c8-1f2e1149af8a.png)
[传送门](https://www.wolai.com/cuixiaorui/33vTWcwzymPyyrzpkaPAgF?theme=dark)
