### ISSUE TITLE
afterain 2021.12.22

### ISSUE THREAD

**Issue by cuiaiguanggh** [cuixiaorui/study-every-day#274]
![image](https://user-images.githubusercontent.com/23047484/147021880-d3d16dab-fb8e-4c76-8b41-a21f63f496ee.png)

**Comment by cuiaiguanggh** [comment]
![image](https://user-images.githubusercontent.com/23047484/147021824-422d73eb-a27c-4c3e-a3d2-ab6e9925abbb.png)

**Comment by cuixiaorui** [comment]
写错位置了
