### ISSUE TITLE
每日计划2021-12-29

### ISSUE THREAD

**Issue by JackenJ** [cuixiaorui/study-every-day#284]
---------------------------------------------------------------
-学习方面

- [x]  每天早晨观看30分钟重构
- [ ] 编写文章，今晚发布
- [ ] 了解VUE3函数应用
- [ ] 观看GITHUB上大佬的代码编写习惯
- [ ] 编写之前的题解
---------------------------------------------------------------
-生活方面

- [ ] 早睡早起
---------------------------------------------------------------

**Comment by JackenJ** [comment]
每日计划2021-12-29

**Comment by Max199909** [comment]
12-29
重点工作
1.看一下能否获取客户端信息
2.看一下1排期，明确排期时间
3.正常开发

自我提升：
1.学习计算机网络；
2.学习vue3源码；
3.leetcode-2

其他：
1.看一下时间，如何请假；
2.俯卧撑50个，晚上回家做，一定
