### ISSUE TITLE
【新人必读】 -- 提议

### ISSUE THREAD

**Issue by Io-tiny** [cuixiaorui/study-every-day#9]
目的： 建立一个高质量的学习和交流的一个平台
1. 每日任务
每日任务主要是记录每日计划与安排，通过分享的方式督促自己
分享的地址为：[链接](https://github.com/cuixiaorui/study-every-day/issues)+当日的学习日报
分享的格式为：截图+可查看地址(推荐使用wolai，wolai注册地址+分享码为https://www.wolai.com/signup?invitation=KPAP633)

**Comment by Senluya** [comment]
个人问题的提问方式

**Comment by hellodqz** [comment]
1,本群的宗旨（主要目的是啥）
2，本群的日常动作（如：提交每日计划，学习讨论）
3，如何参与
4，群规（一些注意事项）

**Comment by Mychen3** [comment]
先思考再提问

**Comment by cuixiaorui** [comment]
已经更新：
- 每日任务说明
- 如何提问
